// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdwlctJSYntvLBNPYs7V0sNK-JSYPm2KQ',
    appId: '1:574115784708:web:e528ef999ccca8984cad51',
    messagingSenderId: '574115784708',
    projectId: 'mazadat-9e27c',
    authDomain: 'mazadat-9e27c.firebaseapp.com',
    storageBucket: 'mazadat-9e27c.appspot.com',
    measurementId: 'G-90F6HY8WGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZEfCwEzhqTv0CkUO41t4jnMfFlRLzak',
    appId: '1:574115784708:android:77ac7a6b0b8ba1384cad51',
    messagingSenderId: '574115784708',
    projectId: 'mazadat-9e27c',
    storageBucket: 'mazadat-9e27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCixQNTLeNix4nfRGmbvLnLY6mUodDd-0A',
    appId: '1:574115784708:ios:7b60d2baadfb75154cad51',
    messagingSenderId: '574115784708',
    projectId: 'mazadat-9e27c',
    storageBucket: 'mazadat-9e27c.appspot.com',
    iosClientId: '574115784708-jjieem86rsrnmucgsq97o4tks6t2itu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCixQNTLeNix4nfRGmbvLnLY6mUodDd-0A',
    appId: '1:574115784708:ios:7b60d2baadfb75154cad51',
    messagingSenderId: '574115784708',
    projectId: 'mazadat-9e27c',
    storageBucket: 'mazadat-9e27c.appspot.com',
    iosClientId: '574115784708-jjieem86rsrnmucgsq97o4tks6t2itu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
